# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protobuf_extension_sample/my_types_package/v1/datatype.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    1,
    '',
    'protobuf_extension_sample/my_types_package/v1/datatype.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<protobuf_extension_sample/my_types_package/v1/datatype.proto\x12-protobuf_extension_sample.my_types_package.v1\x1a google/protobuf/descriptor.proto*\xb4\x01\n\x08\x44\x61taType\x12\x19\n\x15\x44\x41TA_TYPE_UNSPECIFIED\x10\x00\x12\x13\n\x0f\x44\x41TA_TYPE_ARRAY\x10\x01\x12\x12\n\x0e\x44\x41TA_TYPE_BOOL\x10\x02\x12\x12\n\x0e\x44\x41TA_TYPE_CHAR\x10\x03\x12\x12\n\x0e\x44\x41TA_TYPE_DATE\x10\x04\x12\x16\n\x12\x44\x41TA_TYPE_DATETIME\x10\x05\x12\x11\n\rDATA_TYPE_INT\x10\x06\x12\x11\n\rDATA_TYPE_NUM\x10\x07:n\n\x0cmy_data_type\x12\x1d.google.protobuf.FieldOptions\x18\xd1\x86\x03 \x01(\x0e\x32\x37.protobuf_extension_sample.my_types_package.v1.DataTypeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf_extension_sample.my_types_package.v1.datatype_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATATYPE']._serialized_start=146
  _globals['_DATATYPE']._serialized_end=326
# @@protoc_insertion_point(module_scope)
