# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protobuf_extension_sample/my_types_package/datatype.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    1,
    '',
    'protobuf_extension_sample/my_types_package/datatype.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9protobuf_extension_sample/my_types_package/datatype.proto\x12\x10my_types_package\x1a google/protobuf/descriptor.proto*`\n\x08\x44\x61taType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05\x41RRAY\x10\x01\x12\x08\n\x04\x42OOL\x10\x02\x12\x08\n\x04\x43HAR\x10\x03\x12\x08\n\x04\x44\x41TE\x10\x04\x12\x0c\n\x08\x44\x41TETIME\x10\x05\x12\x07\n\x03INT\x10\x06\x12\x07\n\x03NUM\x10\x07:Q\n\x0cmy_data_type\x12\x1d.google.protobuf.FieldOptions\x18\xd1\x86\x03 \x01(\x0e\x32\x1a.my_types_package.DataTypeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf_extension_sample.my_types_package.datatype_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATATYPE']._serialized_start=113
  _globals['_DATATYPE']._serialized_end=209
# @@protoc_insertion_point(module_scope)
