# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protobuf_extension_sample/my_other_package/sample.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    1,
    '',
    'protobuf_extension_sample/my_other_package/sample.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protobuf_extension_sample.my_types_package import datatype_pb2 as protobuf__extension__sample_dot_my__types__package_dot_datatype__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7protobuf_extension_sample/my_other_package/sample.proto\x12\x11my_sample_package\x1a\x39protobuf_extension_sample/my_types_package/datatype.proto\"\xac\x01\n\x06Sample\x12\x12\n\x04\x42ool\x18\x01 \x01(\x08\x42\x04\x88\xb5\x18\x02\x12\x11\n\x03Num\x18\x02 \x01(\x01\x42\x04\x88\xb5\x18\x07\x12\x12\n\x04\x44\x61te\x18\x03 \x01(\x03\x42\x04\x88\xb5\x18\x04\x12\x16\n\x08\x44\x61tetime\x18\x04 \x01(\x03\x42\x04\x88\xb5\x18\x05\x12\x11\n\x03Int\x18\x05 \x01(\x03\x42\x04\x88\xb5\x18\x06\x12\x13\n\x05\x41rray\x18\x06 \x03(\x01\x42\x04\x88\xb5\x18\x01\x12\x12\n\x04\x43har\x18\x07 \x01(\tB\x04\x88\xb5\x18\x03\x12\x13\n\x0bUnsupported\x18\x08 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf_extension_sample.my_other_package.sample_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SAMPLE'].fields_by_name['Bool']._loaded_options = None
  _globals['_SAMPLE'].fields_by_name['Bool']._serialized_options = b'\210\265\030\002'
  _globals['_SAMPLE'].fields_by_name['Num']._loaded_options = None
  _globals['_SAMPLE'].fields_by_name['Num']._serialized_options = b'\210\265\030\007'
  _globals['_SAMPLE'].fields_by_name['Date']._loaded_options = None
  _globals['_SAMPLE'].fields_by_name['Date']._serialized_options = b'\210\265\030\004'
  _globals['_SAMPLE'].fields_by_name['Datetime']._loaded_options = None
  _globals['_SAMPLE'].fields_by_name['Datetime']._serialized_options = b'\210\265\030\005'
  _globals['_SAMPLE'].fields_by_name['Int']._loaded_options = None
  _globals['_SAMPLE'].fields_by_name['Int']._serialized_options = b'\210\265\030\006'
  _globals['_SAMPLE'].fields_by_name['Array']._loaded_options = None
  _globals['_SAMPLE'].fields_by_name['Array']._serialized_options = b'\210\265\030\001'
  _globals['_SAMPLE'].fields_by_name['Char']._loaded_options = None
  _globals['_SAMPLE'].fields_by_name['Char']._serialized_options = b'\210\265\030\003'
  _globals['_SAMPLE']._serialized_start=138
  _globals['_SAMPLE']._serialized_end=310
# @@protoc_insertion_point(module_scope)
